# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'rack-test', '~> 2.1'
  gem 'rake'
  gem 'rspec', '~> 3.13'
  gem 'rubocop', '~> 1.75', require: false
  gem 'rubocop-rspec', '~> 3.9', require: false
  gem 'simplecov', require: false
  gem 'simplecov-cobertura', require: false
  gem 'yard'
  gem 'yard-markdown'

  # Postgres backend: pg is only needed when DATABASE_URL is postgres://.
  # Sequel loads the pg adapter lazily on connect.
  gem 'pg'
  gem 'sequel', '~> 5.0'
end
