# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

# Local gems — remove once published to rubygems
gem 'bsv-wallet', path: '../bsv-wallet'
gem 'bsv-sdk', path: '/opt/ruby/bsv-ruby-sdk/gem/bsv-sdk'

group :development, :test do
  gem 'rspec', '~> 3.13'
  gem 'rack-test', '~> 2.1'
  gem 'rubocop', '~> 1.75', require: false
  gem 'simplecov', require: false
  gem 'simplecov-cobertura', require: false
end
