# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development, :test do
  # Use sibling bsv-wallet from this repo (gemspec has the released dependency)
  gem 'bsv-wallet', path: '../bsv-wallet'
  gem 'rspec', '~> 3.13'
  gem 'rack-test', '~> 2.1'
  gem 'rubocop', '~> 1.75', require: false
  gem 'simplecov', require: false
  gem 'simplecov-cobertura', require: false
end
