# frozen_string_literal: true

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec)

task default: :spec

namespace :db do
  desc 'Run migrations'
  task :migrate do
    require 'sequel'
    Sequel.extension :migration
    db = Sequel.connect(ENV.fetch('DATABASE_URL'))
    Sequel::Migrator.run(db, File.join(__dir__, 'db/migrations'))
  end
end
